### ISSUE TITLE
[Question][Custom Widget] Using custom initial width

### ISSUE THREAD

**Issue by AbdallahHemdan** [DataDog/apps#151]
### 💭 Question
I can see from the documents in [programming model](https://github.com/DataDog/apps/blob/master/docs/en/programming-model.md) that for the `default_size` we only have 3 options `sm`, `md`, and `lg`.

I want to ask if we have an option for adding an initial width using a custom number of `rows` & `columns` to have the widget in size without the extra step of resizing from the user.

![image](https://user-images.githubusercontent.com/40190772/193779351-bda9951b-55db-419b-9867-2a586c5cef93.png)

**Comment by AbdallahHemdan** [comment]
@rachelnicole It would be great if you could support here 🙏🏻

**Comment by AbdallahHemdan** [comment]
@ericrallen, @rachelnicole It would be great if you could support here 🙏🏻

**Comment by AbdallahHemdan** [comment]
@enbashi, @ericrallen, @rachelnicole It would be great if you could help here 🙏🏻

**Comment by joneshf-dd** [comment]
Hey @AbdallahHemdan 👋🏾.

At this point, we are not adding the ability to specify custom rows and columns. As you mentioned, the three options are the predefined `"sm"`, `"md"`, and `"lg"`. However, specifying custom rows and columns is something that may be possible down the line on our roadmap.
