### ISSUE TITLE
PagerDuty app | Customers unable to login

### ISSUE THREAD

**Issue by iddl** [DataDog/apps#162]
⚠️ As of **November 13th 2023** we have confirmed that changes released in all major browsers are blocking unauthenticated users from logging in on the Pagerduty UI. This disruption has started becoming increasingly evident with the gradual rollout of Chrome 115 and above.

We have been working on a few solutions to restore service and we will provide status updates in this thread as we make progress.

For any questions please reply to this thread or email apps@datadoghq.com.
For more technical details follow issue https://github.com/DataDog/apps/issues/160

**Comment by wfa207** [comment]
The external authentication flow has been updated to leverage a modal to facilitate users authenticating with 3rd parties. PagerDuty has confirmed their users are able to authenticate successfully again, and as such, we are closing this issue.
