### ISSUE TITLE
Error status code is not preserved

### ISSUE THREAD

**Issue by ytnytn1** [DataDog/apps#59]
Hello! 

When Datadog API returns an error, the status code is not preserved by the API client.

example of a request that is sent by the Datadog UI that returns 400 error:
https://app.datadoghq.com/api/v1/monitor/search?query=%7B%7D&page=0&per_page=48&sort=name,asc 

response from the API client: `{"errors":["Query parsing error: { is not a valid character"]}`

**Comment by enbashi** [comment]
Thanks for filing this issue. Yes we currently only return the error message from the API client. I added a feature request to return more elaborate error details and we will update you here once we have any updates. Could you please briefly describe your use-case for the error code? Is this a blocker for your app development? I am trying to gauge the urgency and impact of this request.

**Comment by ytnytn1** [comment]
Thank you for replay! 

Here is the use-case:
We have a table with monitors which user can filter using query. The status code is needed to apply different styles to the error message depending on the type of the error. So as we don't have status code we have to use the same styles. 
This is defenetly not a blocker for us.

**Comment by joneshf-dd** [comment]
Sorry for the delay, we just made an update that should give back the status code in an API error response. Given the same query above, it should return an error like:
```
{"errors":["Query parsing error: { is not a valid character"],"status":400}
```

In particular, the `"status"` field contains the status code.

Let us know if you need anything else!
