### ISSUE TITLE
Support of US3 and US5 regions

### ISSUE THREAD

**Issue by ytnytn1** [DataDog/apps#99]
Hello! 

I've received [notification](https://github.com/DataDog/marketplace/issues/290) from the Marketplace team that Datadog Marketplace is now available on Azure US3 and GCP US5 regions.  
Does UI-extension SDK have support of multiple regions ? 
I found hardcoded constant in the source code https://github.com/DataDog/apps/blob/1dba655eaa006ef6b587efaf5912258832f776a0/packages/ui-extensions-sdk/src/constants.ts#L2  But seems it is not used. 

Thanks.

**Comment by ivang-shoreline** [comment]
Hello @nmuldavin, @joneshf-dd! 
Could you please update me about this issue ? 
Thanks!

**Comment by nmuldavin** [comment]
My apologies for the late response. 

Your app will automatically work with datadog instances in azure (us3) and gcp (us5). That HOST enum is actually unused, we need to remove it :)

**Comment by ivang-shoreline** [comment]
Great, thank you!
